version: '3.7'
services:
  naming-server:
    build:
      context: eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    restart: always
  hello-world-service:
    build:
      context: my-hello-world-service
      dockerfile: Dockerfile    
    ports:
      - "8100:8100"
    restart: always
    depends_on:
      - naming-server